production_kaju/kaju/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from kaju import views
from django.urls import path

app_name = "kaju"

urlpatterns = [
    # url(r'^$',views.base,name = 'base'),
    url(r'^$',views.index,name = 'index'),
    # url(r'registration/',views.register,name='register'),
    url(r'^admin/',admin.site.urls),
    url(r'login/',views.user_login,name='login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    # url(r'index/',views.index, name = 'index'),
    url(r'Add_static/',views.add_static, name='add_static'),
    url(r'add_country/',views.add_country,name='add_country'),
    url(r'add_region/',views.add_region,name='add_region'),
    url(r'bucket',views.bucket_vw,name='bucket'),
    url(r'dry_rcn',views.dry_rcn,name='rcn_dry'),
    url(r'processing/',views.processing,name='processing'),
    url(r'climate/', views.day_parameters,name='day_parameters'),
    url(r'cooking/',views.cooking,name = 'cooking'),
    url(r'RCN_avail',views.rcn_avail,name='rcn_avail'),
    url(r'cutting/',views.cutting,name='cutting'),
    url(r'bormah/',views.bormah,name='bormah'),
    url(r'peeling/',views.peeling, name='peeling'),
    url(r'add_grade/',views.add_grade,name ='add_grade'),
    url(r'grading/',views.grading,name='grading'),

]

production_kaju/production_kaju/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from kaju import views

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

urlpatterns = [
    url('',include('kaju.urls')),

]

production_kaju/kaju/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

class UserForm(forms.ModelForm):
    # password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserInfo(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('user',)
class country_form(forms.ModelForm):
    class Meta:
        model = country
        fields = ('country_origin','country_iso')


class region_form(forms.ModelForm):
    class Meta:
        model = region
        fields = ('country','region_name')

class bucket_form(forms.ModelForm):

    class Meta:
        model = bucket
        fields = ('region', 'quantity', 'crop_time', 'price_kg',
                  'purchase_out_turn', 'nut_count','production_out_turn',
                  'moisture', 'drying_req')

class rcn_dry_form(forms.ModelForm):
    class Meta:
        model = RCN_drying
        fields = ('bin_number','no_of_days','moisture_after_drying','quantity_after',
                  'production_out_turn','nut_count_after')




class day_param(forms.ModelForm):
    class Meta:
        model = climate_params
        fields = ('temperature_min', 'temperature_max','humidity','day_type')



class cooking_form(forms.ModelForm):
    class Meta:
        model = processing_lot
        fields =('bucket', 'quantity', 'date_of_position', 'cook_time', 'cook_pressure','foreign_particles','bag_weight')


class cut_form(forms.ModelForm):
    # dropdown = forms.ModelChoiceField(queryset=cutting_section.objects.all())
    class Meta:
        model = cutting_section
        fields = ('date', 'processing_lot', 'rcn_moisture','wholes', 'pieces', 'rejections', 'shells_output', 'pending_quantity',
                  'foreign_particles', 'kernel_moisture')

    # def __init__(self, *args, **kwargs):
    #     super(cut_form, self).__init__(*args,**kwargs)
    #     self.fields['processing_lot'].queryset = cutting_section.objects.exclude(processing_lot__lot_name='Lot1')


class bormah_form(forms.ModelForm):
    class Meta:
        model = bormah
        fields = ('bormah_date','bormah_lot','dried_wholes','dried_pieces')

class peeling_form(forms.ModelForm):
    class Meta:
        model = peeling
        fields = ('peeling_date', 'peeling_lot', 'peeled_wholes', 'peeled_pieces', 'unpeeled_wholes', 'unpeeled_pieces', 'rejections', 'husk')



class grade_name_form(forms.ModelForm):
    class Meta:
        model = grade_names
        fields = ('grade_type','grade_names')

class grading_form(forms.ModelForm):
    class Meta:
        model = grading_section
        fields = ('grading_date','grading_lot')

production_kaju/kaju/views.py
from django.shortcuts import render
from .forms import *
from .models import *
from django.db.models import Q
import ast
# import matploblib.pyplot as plt
import seaborn as sns
import pandas as pd
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.db.models import Subquery as sqr
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
# Create your views here.


# def base(request):
#     return render(request, 'base')
#
# def register(request):
#     registered = False
#     user_form = UserForm()
#     if request.method == "POST":
#         user_form = UserForm(data = request.POST)
#         if user_form.is_valid():
#             user = user_form.save()
#             user.set_password(user.password)
#             user.save()
#             registered = True
#         else:
#             print(user_form.errors)
#     context = {'user_form':user_form,
#                'registered':registered}
#     return render(request, 'kaju/registration.html',context=context)


def index(request):
    return render(request, 'kaju/index.html')

def add_static(request):
    return render(request,'kaju/Add_static.html')

def add_country(request):
    form = country_form()

    if request.method =="POST" :
        form = country_form(request.POST)
        if form.is_valid():
            form.save(commit=True)

    context = {'process':form}
    return render(request,'kaju/add_country.html',context=context)


def add_region(request):
    form = region_form()
    if request.method =="POST" :
        form = region_form(request.POST)
        if form.is_valid():
            form.save(commit=True)



    context = {'process': form}
    return render(request, 'kaju/add_region.html', context=context)


def bucket_vw(request):
    form = bucket_form()
    if request.method =="POST" :
        form = bucket_form(request.POST)
        if form.is_valid():
            form.save(commit=True)


    context = {'process': form}
    return render(request, 'kaju/bucket.html', context=context)

def dry_rcn(request):
    form = rcn_dry_form()
    if request.method =="POST":
        form = rcn_dry_form(request.POST)
        if form.is_valid():
            bkt = request.POST.get('bin_number')
            print('\n\n\n\n\n bkt',bkt)
            bkt_qry = bucket.objects.filter(bucket_id=bkt).values('quantity')
            print(bkt_qry)
            bkt_qty = bkt_qry[0]['quantity']
            print('\n\n\n\n bucket qu', bkt_qty)
            qty = request.POST.get('quantity_after')
            bkt_qry.update(quantity = float(qty))
            form.save(commit=True)
    context = {'process':form}
    return render(request,'kaju/dry_rcn.html',context=context)

def processing(request):
    my_data = processing_lot.objects.all()[2:7]
    my_data_frame = pd.DataFrame(my_data.values())
    # my_data_frame.to_excel('my_data.xlsx')
    piece_per = my_data_frame.pieces*100/(my_data_frame.wholes+my_data_frame.pieces)
    plot = sns.lineplot(x=my_data_frame.lot_name,y=piece_per).get_figure()
    plot.savefig("D:\Production\Production\production_kaju\kaju\static\img\plots\pieces_per.png")
    print(my_data_frame)

    context = {'data': my_data}

    return render(request,'kaju/processing.html',context=context)


def day_parameters(request):
        form = day_param()
        if request.method =="POST":
            form = day_param(request.POST)
            if form.is_valid():
                form.save(commit=True)
        context = {'process':form}
        return render(request,'kaju/climate.html',context = context)


def cooking(request):
    form = cooking_form()
    td_buck = bucket.objects.filter(~Q(quantity = 0)).order_by('-quantity')[:5]
    # print(td_buck)
    if request.method == "POST":
        form = cooking_form(request.POST)
        if form.is_valid():
            bkt = request.POST.get('bucket')
            # print('\n\n\n',bkt)
            bct_qry = bucket.objects.filter(bucket_id=bkt).values('quantity')
            # print('\n\n\n\n bquery',bct_qry)
            bct_qty = bct_qry[0]['quantity']
            qty_2 = request.POST.get('quantity')
            bct_qty = bct_qty - float(qty_2)
            bct_qry.update(quantity = bct_qty)
            form.save(commit=True)


    context = {'process': form,
               'quantity':td_buck}
    return render(request,'kaju/cooking.html',context = context)

def rcn_avail(request):
    td_buck = bucket.objects.filter(~Q(quantity = 0)).order_by('-quantity')
    context = {'quantity':td_buck}
    return render(request,'kaju/RCN_avail.html',context = context)

def cutting(request):
    form = cut_form()


    if request.method == 'POST':
        form = cut_form(request.POST)
        if form.is_valid():
            lot = request.POST.get('processing_lot')

            #PROCESSED QUANTITY
            # print('\n\n\n len:lot', len(lot),' lot: ',lot)
            lot_qry = processing_lot.objects.filter(lot_id=lot).values('quantity')
            lot_pro_qry = processing_lot.objects.filter(lot_id=lot).values('processed')
            # print('\n\n\n\n\n',lot_qry)
            # print('form is valid')
            lot_qty = lot_qry[0]['quantity']
            lot_pro_qty = lot_pro_qry[0]['processed']
            # print('\n\n\n\n\ qty',lot_pro_qty)
            pro_qty = request.POST.get('pending_quantity')
            lot_qty =lot_qty - float(pro_qty)+lot_pro_qty
            pro_qty_up = float(pro_qty)
            # print('\n\n\n\n qty:', lot_qty)
            lot_qry.update(quantity = pro_qty_up)
            lot_qry.update(processed = lot_qty)

            #SHELLS
            lot_shell_qry = processing_lot.objects.filter(lot_id=lot).values('shells')
            lot_shell_qty = lot_shell_qry[0]['shells']
            # print('\n\n\n\n\ qty',lot_pro_qty)
            shell_qty = request.POST.get('shells_output')
            shell_qty_up = float(shell_qty) + lot_shell_qty
            # print('\n\n\n\n qty:', lot_qty)
            lot_shell_qry.update(shells=float(shell_qty_up))

            #WHOLES
            lot_wholes_qry = processing_lot.objects.filter(lot_id=lot).values('wholes')
            lot_wholes_qty = lot_wholes_qry[0]['wholes']
            wholes_qty = request.POST.get('wholes')
            wholes_qty_up = float(wholes_qty) + lot_wholes_qty
            lot_wholes_qry.update(wholes = wholes_qty_up)

            # PIECES
            lot_pieces_qry = processing_lot.objects.filter(lot_id=lot).values('pieces')
            lot_pieces_qty = lot_pieces_qry[0]['pieces']
            # print('\n\n\n\n Pieces:',lot_pieces_qty)
            pieces_qty = request.POST.get('pieces')
            pieces_qty_up = float(pieces_qty) + lot_pieces_qty
            # print('\n\n\n\n Pieces:', pieces_qty_up)
            lot_pieces_qry.update(pieces=pieces_qty_up)

            # REJECTION
            lot_rejection_qry = processing_lot.objects.filter(lot_id=lot).values('rejection')
            lot_rejection_qty = lot_rejection_qry[0]['rejection']
            rejection_qty = request.POST.get('rejections')
            rejection_qty_up = float(rejection_qty) + lot_rejection_qty
            lot_rejection_qry.update(rejection=rejection_qty_up)


            # FOREIGN
            lot_foreign_particles_qry = processing_lot.objects.filter(lot_id=lot).values('foreign_particles')
            # print('\n\n\n fp:',lot_foreign_particles_qry)
            lot_foreign_particles_qty = lot_foreign_particles_qry[0]['foreign_particles']
            # print('\n\n\n\n lfp;',lot_foreign_particles_qty)
            foreign_particles_qty = request.POST.get('foreign_particles')
            foreign_particles_qty_up = float(foreign_particles_qty) + lot_foreign_particles_qty
            lot_foreign_particles_qry.update(foreign_particles=foreign_particles_qty_up)

            # PROCESS TOTAL
            lot_process_total_qry = processing_lot.objects.filter(lot_id=lot).values('process_total')
            lot_process_total_qty = lot_process_total_qry[0]['process_total']
            process_qty = lot_process_total_qty + foreign_particles_qty_up + rejection_qty_up + pieces_qty_up + wholes_qty_up + shell_qty_up
            lot_process_total_qry.update(process_total = process_qty)

            # LOT OUT TURN
            lot_out_turn_qry = processing_lot.objects.filter(lot_id =lot).values('out_turn')
            qty_for_ot = wholes_qty_up + pieces_qty_up
            # print('\n\n\n\n qty:',qty_for_ot)
            qty_for_ot = qty_for_ot*80*2.23/lot_qty
            # print('\n\n\n\n ot:',qty_for_ot)
            lot_out_turn_qry.update(out_turn = qty_for_ot)

            #LOT ADJ
            lot_adj_qry = processing_lot.objects.filter(lot_id=lot).values('adj_cutting')
            # print('\n\n\n process_qty:',lot_qty)
            # print('\n\n\n process_qty_aft:', process_qty)
            adj_qty = lot_qty - process_qty
            lot_adj_qry.update(adj_cutting = adj_qty)

            form.save(commit=True)

    context = {'process':form}

    return render(request, 'kaju/cutting.html', context=context)

def bormah(request):
    form = bormah_form()
    if request.method == "POST":
        form = bormah_form(request.POST)
        if form.is_valid():
            form.save(commit=True)
            lot = request.POST.get('bormah_lot')
            lot_wholes_qry = processing_lot.objects.filter(lot_id = lot).values('dried_wholes')
            lot_pieces_qry = processing_lot.objects.filter(lot_id=lot).values('dried_pieces')
            lot_wholes_qty = lot_wholes_qry[0]['dried_wholes']
            lot_pieces_qty = lot_pieces_qry[0]['dried_pieces']
            form_wholes = request.POST.get('dried_wholes')
            form_pieces = request.POST.get('dried_pieces')
            wholes_up = lot_wholes_qty + float(form_wholes)
            pieces_up = lot_pieces_qty + float(form_pieces)

production_kaju/kaju/templates/kaju/Add_static.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Static_add</title>
    <link rel="stylesheet" href="{%static "/css/bootstrap.min.css" %}">
</head>
<body>

<div class="jumbotron">


    <h1>{% block title %}Add required data here{% endblock%}</h1>


    <div class="container">
        <div id="mySidenav" class="sidenav"><a href="/">Home</a>
        <a href="/add_country" class ="btn">Add Country</a>
        <a href="/add_region" class="btn"><i class="glyphicon glyphicon-globe"></i>Add Region</a>
        <a href="/add_grade" class="btn"><i class="glyphicon glyphicon-globe"></i>Add Grades</a>

<!--        <ul class="sidenav"><li><a href="#" class="btn"><i class="glyphicon glyphicon-globe"></i>Add Region</a></li>-->
<!--        <li><a href="#" class ="btn">Add Country</a></li>-->

<!--        </ul>-->
        </div>
    </div>
</div>
<div class="container">{% block content %}{% endblock %}</div>
</body>
</html>

production_kaju/kaju/templates/kaju/RCN_avail.html
{% extends "kaju/processing.html" %}
{% load static %}
{% block head%} <font color="yellow">Cooking</font> {% endblock%}
{% block content%}

<!--<form method = "POST" onchange="form.submit();">-->
<!--   {% csrf_token %}-->
<!--   {{buck_info.bucket}}-->
<!--&lt;!&ndash;    {{buck_info.quantity}}&ndash;&gt;-->
<!--    <input type="submit" name="check_qty" value="Submit"/></form>-->
<!--<h4>{{quantity}}</h4>-->
<!--&lt;!&ndash;<h4>{{buck_info.quantity.value}}</h4>&ndash;&gt;-->
<div>
    <table style="width:100%">
        <tr>
            <th valign="top"> <h3>Availability</h3> </th>
        </tr>
        <tr>
           <td valign="top">
                <table style="width:100%" class="table">
                    <tr>
                        <th> Bucket</th>
                        <th>Country</th>
                        <th> Quantity</th>
                    </tr>
                    {% for q in quantity %}

                    <tr>
                        <td>{{q.bucket_name}}</td>
                        <td>{{q.region.country}}</td>
                        <td>{{q.quantity}}</td>
                    </tr>
                    {% endfor %}
                </table>

            </td>
        </tr>


    </table>
</div>


<!--<h4>{{quantity}}</h4>-->

{% endblock %}

production_kaju/kaju/templates/kaju/add_country.html
{% extends "kaju/Add_static.html" %}


{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{%static "/css/bootstrap.min.css" %}">
{% endblock stylesheets %}

{% block title %} Add Country {% endblock %}


{% block content%}

<form method="POST">
    {% csrf_token %}
    <h4>{{process.as_p}}</h4>
    <h4><input type="submit" value="Submit"></h4>
</form>



{% endblock %}

production_kaju/kaju/templates/kaju/add_region.html
{% extends "kaju/Add_static.html" %}


{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{%static "/css/bootstrap.min.css" %}">
{% endblock stylesheets %}

{% block title %} Add Country {% endblock %}


{% block content%}

<form method="POST">
    {% csrf_token %}
    <h4>{{process.as_p}}</h4>
    <h4><input type="submit" value="Submit"></h4>
</form>



{% endblock %}

production_kaju/kaju/templates/kaju/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><!DOCTYPE html>

{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Cashew</title>

    <link rel="stylesheet" href="{%static '/css/bootstrap.min.css' %}">


  </head>
  <body>

    <style media="screen">
      body{
        background-image: url("static/img/Cashew 3.jpg");
        background-repeat: no-repeat;
        background-size: 100%;
      }
    </style>

    <div class="container" style="background-image: url("/static/img/Cashew 3.jpg")">
      <div class="jumbotron bg-light text-warning">
        <h1> {% block head %}Home page:{% endblock %} </h1>
        <div class="container text-dark">

          <p></p>
        </div>

        <div class="container">
          <ul class="nav navbar-nav">
              <li><a class="navbar-brand" href="/index">Kaju</a></li>
              <li><a class="navbar-link" href="/registration">Register</a></li>
            {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">log_out</a></li>
            {% else %}
            <li><a class="navbar-link" href="{% url 'kaju:login' %}">Login</a></li>
            {% endif %}
            


          </ul>

        </div class = "container">
          <div>{% block body_block%} {% endblock %}</div>

      </div>
    </div>
    <div class="container">{% block content %} {% endblock %}</div>


  </body>
</html>
</title>
</head>
<body>

</body>
</html>

production_kaju/kaju/templates/kaju/cooking.html
{% extends "kaju/processing.html" %}
{% load static %}
{% block head%} <font color="yellow">Cooking</font> {% endblock%}
{% block content%}

<div>
    <table style="width:100%">
        <tr>
            <th valign="top"> <h3>Form</h3> </th>
            <th valign="top"> <h3>Availability</h3> </th>
        </tr>
        <tr>
            <td>
                <form method = "POST">
                    {% csrf_token %}

                    <h5> {{process.as_p}}</h5>
                    <h5><input type="submit" name="submit_form" value="Submit"></h5>
                </form>
            </td>
            <td valign="top">
                <table style="width:100%" class="table">
                    <tr>
                        <th> Bucket</th>
                        <th>Country</th>
                        <th> Quantity</th>
                    </tr>
                    {% for q in quantity %}

                    <tr>
                        <td>{{q.bucket_name}}</td>
                        <td>{{q.region.country}}</td>
                        <td>{{q.quantity}}</td>
                    </tr>

                    {% endfor %}
                    <tr><a class = "btn btn-info btn-lg " href="/RCN_avail">More Buckets</a></tr>
                </table>


            </td>
        </tr>


    </table>
</div>


<!--<h4>{{quantity}}</h4>-->

{% endblock %}

production_kaju/kaju/templates/kaju/cutting.html
{% extends "kaju/processing.html" %}
{% load static %}
{% block head%} <font color="orange">Cutting</font> {% endblock%}
{% block content%}

<div>
  <form method="POST">
    {% csrf_token %}
    {{process.as_p}}
    <input type="submit" name="submit_form" value="Submit">
  </form>
</div>


{% endblock %}

production_kaju/kaju/templates/kaju/dry_rcn.html
{% extends "kaju/index.html" %}
{% load static %}
{% block head%} Dry RCN {% endblock%}
{% block content%}
<!--{% csrf_token %}-->
<!--<form method = "POST">{{process.bucket}}</form>-->
    <form method = "POST">
        {% csrf_token %}
        <h4> {{process.as_p}}</h4>
        <h4><input type="submit" name="submit" value="submit"></h4>
    </form>

{% endblock %}

production_kaju/kaju/templates/kaju/grading.html
{% extends "kaju/processing.html" %}
{% load static %}
{% block head%} <font color="Green">Grading</font> {% endblock%}
{% block content%}

<div>
  <form method="POST">
      {% csrf_token %}

      <table class="table table-striped table-hover">
          <tr>
              <td> Date:</td>
              <td>{{process.grading_date}}</td>
          </tr>
          <tr>
              <td>Lot:</td>
              <td>{{process.grading_lot}}</td>
          </tr>
          <tr class="table-info">
<!--              <th> Wholes/Pieces </th>-->
              <th> Grade</th>
              <th> Quantity</th>
          </tr>
          {% for grade in grades %}
          <tr>
<!--            <td>{{grade.grade_type}}</td>-->
            <td>{{grade.grade_names}}:</td>
            <td><input type="number" name = "grade-{{forloop.counter}}"></td>
          </tr>
      {% endfor %}




      </table>

<!--    {{process.as_p}}-->
    <input type="submit" name="submit_form" value="Submit" class = " btn-info">
  </form>
</div>


{% endblock %}

production_kaju/kaju/templates/kaju/index.html
<!DOCTYPE html>

{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Cashew</title>

    <link rel="stylesheet" href="{%static '/css/bootstrap.min.css' %}">


  </head>
  <body>

    <style media="screen">
      body{
        background-image: url("static/img/Cashew 3.jpg");
        background-repeat: no-repeat;
        background-size: 100%;
      }
    </style>

    <div class="container" style="background-image: url("/static/img/Cashew 3.jpg")">
      <div class="jumbotron bg-light text-warning">
        <h1> {% block head %}Home page:{% endblock %} </h1>
        <div class="container text-dark">

          <p></p>
        </div>

        <div class="container">
          <a href="/" class = "btn btn-info btn-lg ">Home</a>
          <a href="/bucket" class = "btn btn-warning btn-lg ">Purchase</a>
          <a href="/processing" class = "btn btn-success btn-lg ">Processing</a>
          <a href="/stock" class = "btn btn-danger btn-lg ">Stock</a>
          <a href="/info" class = "btn btn-info btn-lg ">Customer Info</a>
          <a href="/Add_static" class = "btn btn-danger btn-lg ">Add_static</a>


        </div>

      </div>
    </div>
    <div class="container">{% block content %} {% endblock %}</div>


  </body>
</html>

production_kaju/kaju/templates/kaju/login.html
{% extends "kaju/base.html" %}

{% block body_block %}
<div class="jumbotron">

    <h4> Please login Here </h4>
    <form action="{% url 'kaju:login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter your username">
        <label for="password">Password:</label>
        <input type="text" name="password" placeholder="Enter your Password">

        <input type="submit" value="Login">
    </form>
</div>
{% endblock %}

production_kaju/kaju/templates/kaju/peeling.html
{% extends "kaju/processing.html" %}
{% load static %}
{% block head%} <font color="Blue">Peeling</font> {% endblock%}
{% block content%}

<div>
  <form method="POST">
    {% csrf_token %}
    {{process.as_p}}
    <input type="submit" name="submit_form" value="Submit">
  </form>
</div>


{% endblock %}

production_kaju/kaju/templates/kaju/processing.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Processing</title>
    <link rel="stylesheet" href="{%static '/css/bootstrap.min.css' %}">
</head>
<body>
    <style media="screen">
      body{
        background-image: url("static/img/Cashew 1.jpg");
        background-repeat: no-repeat;
        background-size: 100%;
      }
    </style>
<div class="container" style="background-image: url("/static/img/Cashew 3.jpg")">
      <div class="jumbotron bg-light text-warning">
        <h1> {% block head %} <font color="green">Processing</font>{% endblock %} </h1>
        <div class="container text-dark">

          <p></p>
        </div>

        <div class="container">
          <a href="/" class = "btn btn-info btn-lg ">Home</a>
          <a href="/climate" class = "btn btn-success btn-lg ">Climate</a>
          <a href="/cooking" class = "btn btn-warning btn-lg ">Cooking</a>
          <a href="/cutting" class = "btn btn-danger btn-lg ">Cutting</a>
          <a href="/bormah" class = "btn btn-info btn-lg ">Bormah</a>
          <a href="/peeling" class = "btn btn-warning btn-lg ">Peeling</a>
          <a href="/grading" class = "btn btn-success btn-lg ">Grading</a>
          <a href="/Add_static" class = "btn btn-danger btn-lg ">Add_static</a>


        </div>

      </div>
    </div>
    <div class="container">{% block content %}
        <div class="container">
        <table style="width:100%" class="table ">
            <tr>
                <th><h4>Data</h4></th>
                <th><h4>Plot</h4></th>

            </tr>
            <tr>
                <td>
                    <table class="table table-striped table-hover ">
                        <thead>
                        <tr>
                            <th>Lot</th>
                            <th>Quantity</th>
                            <th>Wholes</th>
                            <th>Pieces</th>
                            <th>Out-turn</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for d in data %}
                        <tr>
                            <td>{{d.lot_name}}</td>
                            <td>{{d.lot_quantity}}</td>
                            <td>{{d.wholes}}</td>
                            <td>{{d.pieces}}</td>
                            <td>{{d.out_turn|floatformat:2}}</td>
                        </tr>
                        {% endfor %}
                        </tbody>

                    </table>
                </td>
                <td><img src= "{% static "img/plots/pieces_per.png"%}" alt=""  height= "300" width="500"></td>
            </tr>
        </table>
            </div>
<!--        {{plot}}-->

        {% endblock %}</div>



</body>
</html>

production_kaju/kaju/templates/kaju/purchase.html
<!DOCTYPE html>

{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Purchase</title>
    <link rel="stylesheet" href="{%static "/css/bootstrap.min.css" %}">
  </head>
  <body>
    <style media="screen">
      body{
        background-image: url("/static/img/store.jpg");
        background-repeat: no-repeat;
        background-size: 100%;
      }
    </style>
    <div class="container">
      <div class="jumbotron bg-warning">
        <h1>Purchase</h1>
        <div class="container">
          <a href="http://127.0.0.1:8000/" class = "btn btn-default btn-light">Home</a>

        </div>

      </div>
    </div>
    <div class="container bg-light py-3">

      <form name="purform" method="post">
        <table border="2">
          {% csrf_token %}
          {{purchase}}
        </table>
        <p></p>
        <p></p>
        <input type="submit" name="" value="Submit" class="btn btn-primary" onclick="submitForm()">
        <script>
            function submitForm() {
            document.perform.submit();
            document.perform.reset();
            }
        </script>

      </form>


      <!-- {% for field in purchase%}

      {{ field.item}}
      {{ field.units}}

      {% endfor %} -->



    </div>

  </body>
</html>